import { Injectable, signal, computed } from '@angular/core';

export type Lang = 'pl' | 'en';

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  pl: {
    'app.title': 'Listy zakupów',
    'app.my_lists': 'Moje listy',
    'app.shared_lists': 'Udostępnione mi',
    'app.new_list': 'Nowa lista',
    'app.archive': 'Archiwum',
    'app.from_template': 'Z szablonu',
    'app.templates': 'Szablony',
    'app.save_template': 'Zapisz jako szablon',
    'app.stats': 'Statystyki',
    'app.profile': 'Profil',
    'app.login': 'Zaloguj się',
    'app.logout': 'Wyloguj',
    'app.theme_dark': 'Tryb ciemny',
    'app.theme_light': 'Tryb jasny',
    'app.empty_my_lists': 'Nie masz jeszcze żadnych list zakupów.',
    'app.empty_shared': 'Nie masz jeszcze żadnych udostępnionych list.',
    'app.create_first': 'Utwórz nową listę, aby zacząć!',
    'app.list_name': 'Nazwa listy',
    'app.create': 'Utwórz',
    'app.cancel': 'Anuluj',
    'app.products': 'Produkty',
    'app.created': 'Utworzono',
    'app.shared_badge': 'Udostępnione',
    'app.delete_list': 'Usuń listę',
    'list.back': 'Wróć',
    'list.share': 'Udostępnij listę',
    'list.options': 'Opcje listy',
    'list.filter': 'Filtruj',
    'list.sort': 'Sortuj',
    'list.all': 'Wszystkie',
    'list.purchased': 'Kupione',
    'list.not_purchased': 'Nie kupione',
    'list.sort_name': 'Nazwa',
    'list.sort_category': 'Kategoria',
    'list.sort_priority': 'Priorytet',
    'list.sort_status': 'Status',
    'list.uncheck_all': 'Odhacz wszystkie',
    'list.search_products': 'Szukaj na liście...',
    'list.empty_products': 'Brak produktów w tej liście.',
    'list.add_products': 'Dodaj produkty używając wyszukiwarki powyżej.',
    'list.quantity': 'Ilość',
    'list.price': 'Cena',
    'list.note': 'Notatka',
    'list.save': 'Zapisz',
    'list.delete': 'Usuń',
    'list.edit': 'Edytuj',
    'list.theme': 'Motyw',
    'list.theme_dark': 'ciemny',
    'list.theme_light': 'jasny',
    'list.rename': 'Zmień nazwę listy',
    'list.check_all': 'Zaznacz wszystkie produkty',
    'list.uncheck_all_btn': 'Odhacz wszystkie produkty',
    'list.remove_purchased': 'Usuń kupione produkty',
    'menu.rename': 'Zmień nazwę listy',
    'menu.share': 'Udostępnij',
    'menu.archive': 'Archiwuj listę',
    'menu.unarchive': 'Przywróć z archiwum',
    'menu.save_template': 'Zapisz jako szablon',
    'template.name': 'Nazwa szablonu',
    'template.create_from': 'Utwórz listę z szablonu',
    'stats.title': 'Statystyki',
    'stats.total_lists': 'Łącznie list',
    'stats.archived': 'W archiwum',
    'stats.total_products': 'Produkty łącznie',
    'stats.by_category': 'Według kategorii',
    'stats.estimated_cost': 'Szacowany koszt',
    'demo.limit_lists': 'Osiągnięto limit konta demo (max 2 listy). Załóż konto, aby mieć więcej.',
    'demo.limit_products': 'Osiągnięto limit produktów na liście (max 10 w wersji demo).',
    'demo.reset': 'Zresetuj dane demo',
    'demo.reset_done': 'Dane demo zresetowane.',
    'confirm.delete_list': 'Czy na pewno chcesz usunąć tę listę?',
    'confirm.delete_product': 'Czy na pewno chcesz usunąć ten produkt?',
    'confirm.uncheck_all': 'Czy na pewno chcesz odznaczyć wszystkie produkty?',
    'confirm.remove_purchased': 'Czy na pewno chcesz usunąć wszystkie kupione produkty z tej listy?',
    'app.no_archived': 'Brak zarchiwizowanych list.',
    'app.restore': 'Przywróć',
    'app.no_templates': 'Brak zapisanych szablonów.',
  },
  en: {
    'app.title': 'Shopping lists',
    'app.my_lists': 'My lists',
    'app.shared_lists': 'Shared with me',
    'app.new_list': 'New list',
    'app.archive': 'Archive',
    'app.from_template': 'From template',
    'app.templates': 'Templates',
    'app.save_template': 'Save as template',
    'app.stats': 'Statistics',
    'app.profile': 'Profile',
    'app.login': 'Log in',
    'app.logout': 'Log out',
    'app.theme_dark': 'Dark mode',
    'app.theme_light': 'Light mode',
    'app.empty_my_lists': "You don't have any shopping lists yet.",
    'app.empty_shared': "You don't have any shared lists yet.",
    'app.create_first': 'Create a new list to get started!',
    'app.list_name': 'List name',
    'app.create': 'Create',
    'app.cancel': 'Cancel',
    'app.products': 'Products',
    'app.created': 'Created',
    'app.shared_badge': 'Shared',
    'app.delete_list': 'Delete list',
    'list.back': 'Back',
    'list.share': 'Share list',
    'list.options': 'List options',
    'list.filter': 'Filter',
    'list.sort': 'Sort',
    'list.all': 'All',
    'list.purchased': 'Purchased',
    'list.not_purchased': 'Not purchased',
    'list.sort_name': 'Name',
    'list.sort_category': 'Category',
    'list.sort_priority': 'Priority',
    'list.sort_status': 'Status',
    'list.uncheck_all': 'Uncheck all',
    'list.search_products': 'Search in list...',
    'list.empty_products': 'No products on this list.',
    'list.add_products': 'Add products using the search above.',
    'list.quantity': 'Quantity',
    'list.price': 'Price',
    'list.note': 'Note',
    'list.save': 'Save',
    'list.delete': 'Delete',
    'list.edit': 'Edit',
    'list.theme': 'Theme',
    'list.theme_dark': 'dark',
    'list.theme_light': 'light',
    'list.rename': 'Rename list',
    'list.check_all': 'Check all products',
    'list.uncheck_all_btn': 'Uncheck all products',
    'list.remove_purchased': 'Remove purchased products',
    'menu.rename': 'Rename list',
    'menu.share': 'Share',
    'menu.archive': 'Archive list',
    'menu.unarchive': 'Restore from archive',
    'menu.save_template': 'Save as template',
    'template.name': 'Template name',
    'template.create_from': 'Create list from template',
    'stats.title': 'Statistics',
    'stats.total_lists': 'Total lists',
    'stats.archived': 'In archive',
    'stats.total_products': 'Total products',
    'stats.by_category': 'By category',
    'stats.estimated_cost': 'Estimated cost',
    'demo.limit_lists': 'Demo account limit reached (max 2 lists). Sign up for more.',
    'demo.limit_products': 'Product limit per list reached (max 10 in demo).',
    'demo.reset': 'Reset demo data',
    'demo.reset_done': 'Demo data reset.',
    'confirm.delete_list': 'Are you sure you want to delete this list?',
    'confirm.delete_product': 'Are you sure you want to delete this product?',
    'confirm.uncheck_all': 'Are you sure you want to uncheck all products?',
    'confirm.remove_purchased': 'Are you sure you want to remove all purchased products from this list?',
    'app.no_archived': 'No archived lists.',
    'app.restore': 'Restore',
    'app.no_templates': 'No saved templates.',
  }
};

@Injectable({ providedIn: 'root' })
export class TranslateService {
  private readonly LANG_KEY = 'app_lang';
  private lang = signal<Lang>('pl');

  constructor() {
    const saved = localStorage.getItem(this.LANG_KEY) as Lang | null;
    if (saved === 'pl' || saved === 'en') {
      this.lang.set(saved);
    }
  }

  currentLang = computed(() => this.lang());

  setLang(l: Lang): void {
    this.lang.set(l);
    localStorage.setItem(this.LANG_KEY, l);
  }

  get(key: string): string {
    const l = this.lang();
    return TRANSLATIONS[l]?.[key] ?? key;
  }
}
